# Generated by Django 2.2.2 on 2019-08-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='college_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='college',
            field=models.CharField(max_length=100),
        ),
    ]
